// drip-songs.js
window.collabSongs = [
  // ...

  { // Migliori Collaborazioni del decennio, che Hit
    // è acnhe l'album di Ghali, che lui da solo vale per 4
    title: "Bimbi",
    artist: "Charlie Charles - ft. Izi, Rkomi, Sfera Ebbasta, Tedua, Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Charlie%20Charles%20-%20Bimbi%20ft.%20Izi%2C%20Rkomi%2C%20Sfera%20Ebbasta%2C%20Tedua%2C%20Ghali.mp3",
  },
  {
    title: "ELEGANTE",
    artist: "DrefGold, Sfera Ebbasta - (Prod. Daves The Kid & Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/DrefGold%2C%20Sfera%20Ebbasta%20-%20ELEGANTE%20(Prod.%20Daves%20The%20Kid%20%26%20Charlie%20Charles).mp3",
  },
  {
    title: "Habibi",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20%20-%20Habibi%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Lacrime",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20%20-%20Lacrime%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Ricchi Dentro",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20%20Ricchi%20Dentro%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Barcellona",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Barcellona%20(Official%20Video).mp3",
  },
  {
    title: "Boogieman",
    artist: "Ghali feat. Salmo",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Boogieman%20feat.%20Salmo%20(Official%20Video).mp3",
  },
  {
    title: "Boulevard",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Boulevard%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Buonasera",
    artist: "Ghali - (feat. Soolking)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Buonasera%20(feat.%20Soolking)%20%5BLyric%20Video%5D.mp3",
  },
  {
    title: "Cacao",
    artist: "Ghali feat. Dylan",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Cacao%20feat.%20Dylan%20(Lyrics%20Video).mp3",
  },
  {
    title: "CASA MIA",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20CASA%20MIA%20(Official%20Video).mp3",
  },
  {
    title: "Come Milano",
    artist: "Ghali ft. Charlie Charles",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Come%20Milano%20ft.%20Charlie%20Charles%20(Official%20Audio%20Visualizer).mp3",
  },
  {
    title: "Dende",
    artist: "Ghali - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Dende%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "DNA",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20DNA%20(Lyrics%20Video).mp3",
  },
  {
    title: "Fast Food",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Fast%20Food%20(Lyrics%20Video).mp3",
  },
  {
    title: "Flashback",
    artist: "GHALI",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Flashback.mp3",
  },
  {
    title: "Good Times",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Good%20Times%20(Lyrics%20Video).mp3",
  },
  {
    title: "Happy Days",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Happy%20Days%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "I Love You",
    artist: "GHALI",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20I%20Love%20You.mp3",
  },
  {
    title: "Libertè",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Libert%C3%A8%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Mamma",
    artist: "Ghali - (Prod. Fawzi)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Mamma%20(Prod.%20Fawzi).mp3",
  },
  {
    title: "Marijuana",
    artist: "Ghali - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Marijuana%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Marymango",
    artist: "Ghali feat. tha Supreme (prod. AVA & tha Supreme)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Marymango%20feat.%20tha%20Supreme%20(Official%20Video)%20(prod.%20AVA%20%26%20tha%20Supreme).mp3",
  },
  {
    title: "Milano",
    artist: "Ghali - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Milano%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Niente Panico",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Niente%20Panico%20(Official%20Video).mp3",
  },
  {
    title: "Ninna Nanna",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Ninna%20Nanna%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Non Lo So",
    artist: "Ghali feat Izi- (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Non%20Lo%20So%20ft%20Izi%20(Prod.%20Chris%20Nolan).mp3",
  },
  {
    title: "Ora D'Aria",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Ora%20D'Aria%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Paprika",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Paprika%20(Official%20Video).mp3",
  },
  {
    title: "Pizza Kebab",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Pizza%20Kebab%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Safi Safi",
    artist: "Ghali - (feat. Draganov)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Safi%20Safi%20(feat.%20Draganov)%20%5BLyric%20Video%5D.mp3",
  },
  {
    title: "Senza Pietà",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Senza%20Piet%C3%A0%20(Lyric%20Video).mp3",
  },
  {
    title: "Sto",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Sto%20(Official%20Video).mp3",
  },
  {
    title: "Turbococco",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Turbococco%20(Official%20Video).mp3",
  },
  {
    title: "Vida",
    artist: "GHALI - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/GHALI%20-%20Vida%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Wallah",
    artist: "Ghali",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Wallah%20%5BOfficial%20Video%5D.mp3",
  },
  {
    title: "Wily Wily",
    artist: "Ghali - (Prod. Charlie Charles)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Wily%20Wily%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Zingarello",
    artist: "Ghali - (Prod. Sick Luke)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20-%20Zingarello%20(Prod.%20Sick%20Luke).mp3",
  },
  {
    title: "BAYNA",
    artist: "Ghali - (prod. Rat Chopper)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20%E2%80%93%20BAYNA%20%20(prod.%20Rat%20Chopper)%20%5BLyrics%20Video%5D.mp3",
  },
  {
    title: "DRARI",
    artist: "Ghali feat. Baby Gang (prod. Fawzi)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20%E2%80%93%20DRARI%20feat.%20Baby%20Gang%20(prod.%20Fawzi)%20%5BLyrics%20Video%5D.mp3",
  },
  {
    title: "PARE",
    artist: "Ghali feat. Madame (prod. ITACA)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Ghali%20%E2%80%93%20PARE%20feat.%20Madame%20(prod.%20ITACA)%20%5BOfficial%20Video%5D.mp3",
  },
  {
    title: "Cookies N' Cream",
    artist: "Guè, ANNA, Sfera Ebbasta",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Gu%C3%A8%2C%20ANNA%2C%20Sfera%20Ebbasta%20-%20Cookies%20N'%20Cream.mp3",
  },
  {
    title: "Oh Mamma Mia",
    artist: "Guè, Rose Villain",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Gu%C3%A8%2C%20Rose%20Villain%20-%20Oh%20Mamma%20Mia.mp3",
  },
  {
    title: "Chico",
    artist: "Guè, Rose Villain, Luchè",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Gu%C3%A8%2C%20Rose%20Villain%2C%20Luch%C3%A8%20-%20Chico%20(Visual).mp3",
  },
  {
    title: "Meravigliosa",
    artist: "Guè, Stadio",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Gu%C3%A8%2C%20Stadio%20-%20Meravigliosa.mp3",
  },
  {
    title: "Run It Up",
    artist: "Hanumankind - ( Prod. By Kalmi )",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Hanumankind%20-%20Run%20It%20Up%20(%20Prod.%20By%20Kalmi%20)%20%20%20(Official%20Music%20Video).mp3",
  },
  {
    title: "HO PAURA DI USCIRE",
    artist: "Autore",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/HO%20PAURA%20DI%20USCIRE.mp3",
  },
  {
    title: "IL CIELO NELLA STANZA",
    artist: "Autore",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/IL%20CIELO%20NELLA%20STANZA.mp3",
  },
  {
    title: "CANI RANDAGI",
    artist: "Autore",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Il%20Tre%20-%20CANI%20RANDAGI%20(Visual%20Video).mp3",
  },
  {
    title: "FRAGILI",
    artist: "Il tre - (Official Video - Sanremo 2024)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Il%20Tre%20-%20FRAGILI%20(Official%20Video%20-%20Sanremo%202024).mp3",
  },
  {
    title: "Chic",
    artist: "Izi - (Prod. Mace & Shablo)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Izi%20-%20Chic%20(Prod.%20Mace%20%26%20Shablo)%20(Official%20Video).mp3",
  },
  {
    title: "Fumo Da Solo",
    artist: "Izi - (prod. by Charlie Charles & tha Supreme)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Izi%20-%20Fumo%20Da%20Solo%20(prod.%20by%20Charlie%20Charles%20%26%20tha%20Supreme).mp3",
  },
  {
    title: "Wild Bandana",
    artist: "Izi - (feat. Tedua & Vaz Tè) ft. Tedua, Vaz Tè",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Izi%20-%20Wild%20Bandana%20(feat.%20Tedua%20%26%20Vaz%20T%C3%A8)%20ft.%20Tedua%2C%20Vaz%20T%C3%A8.mp3",
  },
  {
    title: "Insane",
    artist: "Jake Daniels - (ft. Silent Child)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Jake%20Daniels%20-%20Insane%20(ft.%20Silent%20Child).mp3",
  },
  {
    title: "Massafghanistan",
    artist: "Kid Yugi, Night Skinny",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Kid%20Yugi%2C%20Night%20Skinny%20-%20Massafghanistan.mp3",
  },
  {
    title: "100 MESSAGGI",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20100%20MESSAGGI.mp3",
  },
  {
    title: "BUIO DAVANTI",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20BUIO%20DAVANTI%20(Visual).mp3",
  },
  {
    title: "DOLCEVITA",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20DOLCEVITA%20(Visual).mp3",
  },
  {
    title: "HOT",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20HOT%20(Visual).mp3",
  },
  {
    title: "J",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20J.mp3",
  },
  {
    title: "MOB",
    artist: "LZZA feat. SALMO & NITRO (Prod. 333 Mob)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/LAZZA%20-%20MOB%20feat.%20SALMO%20%26%20NITRO%20(Prod.%20333%20Mob).mp3",
  },
  {
    title: "MOLOTOV",
    artist: "Lazza - (Concertos)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20MOLOTOV%20(Concertos).mp3",
  },
  {
    title: "Netflix",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20Netflix.mp3",
  },
  {
    title: "Porto Cervo",
    artist: "Lazza - (prod. 333 Mob)",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20Porto%20Cervo%20(prod.%20333%20Mob).mp3",
  },
  {
    title: "REPLAY",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20REPLAY%20(Visual).mp3",
  },
  {
    title: "SENZA RUMORE",
    artist: "Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%20-%20SENZA%20RUMORE%20(Visual).mp3",
  },
  {
    title: "NESSUNO",
    artist: "Lazza, Geolier",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%2C%20Geolier%20-%20NESSUNO%20(Visual).mp3",
  },
  {
    title: "ZERI IN PIÙ",
    artist: "Lazza, Laura Pausini",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%2C%20Laura%20Pausini%20-%20ZERI%20IN%20PI%C3%99%20(LOCURA).mp3",
  },
  {
    title: "-3 (PERDERE IL VOLO)",
    artist: "Lazza, Marracash",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%2C%20Marracash%20-%20-3%20(PERDERE%20IL%20VOLO)%20(Visual).mp3",
  },
  {
    title: "TOPBOY",
    artist: "Lazza, Noy Narcos",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Lazza%2C%20Noyz%20Narcos%20-%20TOPBOY%20(Visual).mp3",
  },
  {
    title: "Scooteroni RMX",
    artist: "Marracash & Guè - ft. Sfera Ebbasta",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Marracash%20%26%20Gu%C3%A8%20-%20Scooteroni%20RMX%20ft.%20Sfera%20Ebbasta.mp3",
  },
  {
    title: "no vabbè",
    artist: "Rose Villain feat. Lazza",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Rose%20Villain%20-%20no%20vabb%C3%A8%20feat.%20Lazza%20(Official%20Video).mp3",
  },
  {
    title: "MOLECOLE SPRITE",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/SFERA%20EBBASTA%20%26%20SHIVA%20-%20MOLECOLE%20SPRITE%20(Audio).mp3",
  },
  {
    title: "Sciroppo",
    artist:
      "Sfera Ebbasta ft DrefGold (Prod. Charlie Charles, Daves The Kid) ft. DrefGold",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Sfera%20Ebbasta%20-%20Sciroppo%20ft%20DrefGold%20(Prod.%20Charlie%20Charles%2C%20Daves%20The%20Kid)%20ft.%20DrefGold.mp3",
  },
  {
    title: "G63",
    artist: "Sfera Ebbasta, Lazza, Shiva",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Sfera%20Ebbasta%2C%20Lazza%2C%20Shiva%20-%20G63%20(Visual).mp3",
  },
  {
    title: "Hoe",
    artist: "Tedua ft. Sfera Ebbasta",
    category: "Best Collab",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%92%A3%20Best%20Collab%20IT/Tedua%20-%20Hoe%20(Visual%20Video)%20ft.%20Sfera%20Ebbasta.mp3",
  },
];
