// drip-songs.js
window.sferaSongs = [
  // ...
  
  { // Playlist di Sfera Ebbasta il Trapking italiano
    // Playlist 🎤 Sfera Ebbasta Vibes
    title: "MILANO",
    artist: "BIA, Sfera Ebbasta,...",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/BIA,%20Sfera%20Ebbasta,%20Fivio%20Foreign%20-%20MILANO%20(Official%20Music%20Video).mp3",
  },
  {
    title: "Calipso (with Dardust)",
    artist: "Charlie Charles ft. Sfera Ebbasta, Mahmood, Fabri Fibra",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Charlie%20Charles%20-%20Calipso%20(with%20Dardust)%20ft.%20Sfera%20Ebbasta,%20Mahmood,%20Fabri%20Fibra.mp3",
  },
  {
    title: "Tutto apposto",
    artist: "IZI ft. Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Izi%20-%20Tutto%20apposto%20ft.%20Sfera%20Ebbasta.mp3",
  },
  {
    title: "Gigolò ft. Sfera",
    artist: "Lazza - Sfera Ebbasta, Capo Plaza",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Lazza%20-%20Gigol%C3%B2%20ft.%20Sfera%20Ebbasta,%20Capo%20Plaza.mp3",
  },
  {
    title: "FENTANYL",
    artist: "Lazza, Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Lazza,%20Sfera%20Ebbasta%20-%20FENTANYL%20(VIsual).mp3",
  },
  {
    title: "SUPREME",
    artist: "Marracash - tha Supreme, Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Marracash%20-%20SUPREME%20-%20L'ego%20ft.%20tha%20Supreme,%20Sfera%20Ebbasta.mp3",
  },
  {
    title: "CENERE ma è una dedicata a CICCIOGAMER",
    artist: "Nervy",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Nervy%20-%20CENERE%20ma%20%C3%A8%20una%20dedica%20a%20CICCIOGAMER.mp3",
  },

  {
    title: "Pablo",
    artist: "Rvssian x Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Rvssian%20x%20Sfera%20Ebbasta%20-%20Pablo.mp3",
  },
  {
    title: "VVS CARTIER",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/SFERA%20EBBASTA%20&%20SHIVA%20-%20VVS%20CARTIER%20(Audio).mp3",
  },
  {
    title: "Happy Birthday",
    artist: "Sfera Ebbasta - (Prod. Rvssian, Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20%20-%20Happy%20Birthday%20(Prod.%20Rvssian,%20Charlie%20Charles).mp3",
  },
  {
    title: "$€ Freestyle",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20$%E2%82%AC%20Freestyle%20(Visual).mp3",
  },
  {
    title: "20 Collane",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%2020%20Collane%20(Visual).mp3",
  },
  {
    title: "BHMG",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20BHMG%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "BRNBQ",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20BRNBQ%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Bang Bang",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles, Chris Nolan)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Bang%20Bang%20(Prod.%20Charlie%20Charles,%20Chris%20Nolan).mp3",
  },
  {
    title: "Bottiglie Privè",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Bottiglie%20Priv%C3%A8.mp3",
  },
  {
    title: "Cupido",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Cupido%20(Visual)%20ft.%20Quavo.mp3",
  },
  {
    title: "Dexter",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles, Sick Luke)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Dexter%20(Prod.%20Charlie%20Charles,%20Sick%20Luke).mp3",
  },
  {
    title: "Figli Di Papà",
    artist: "Sfera Ebbasta (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Figli%20Di%20Pap%C3%A0%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Gelosi",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Gelosi%20(Visual).mp3",
  },
  {
    title: "Macarena",
    artist: "Sfera Ebbasta ft. Offset",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Macarena%20ft.%20Offset.mp3",
  },
  {
    title: "Notti",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Notti%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Ricchi X Sempre",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Ricchi%20X%20Sempre%20(Visual).mp3",
  },
  {
    title: "Rockstar",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Rockstar%20(Visual).mp3",
  },
  {
    title: "Serpenti A Sonagli",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Serpenti%20A%20Sonagli%20(Visual).mp3",
  },
  {
    title: "Tik Tok RMX",
    artist: "Sfera Ebbasta - (feat. Marracash, Guè Pequeno, Paky & Geolier)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Tik%20Tok%20RMX%20(feat.%20Marracash,%20Gu%C3%A8%20Pequeno,%20Paky%20&%20Geolier).mp3",
  },
  {
    title: "Tran Tran",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Tran%20Tran%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "UHLALA",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20UHLALA%20(Visual).mp3",
  },
  {
    title: "Uber",
    artist: "Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Uber%20(Visual).mp3",
  },
  {
    title: "Visiera A Becco",
    artist: "Sfera Ebbasta - (Prod. Charlie Charles)",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta%20-%20Visiera%20A%20Becco%20(Prod.%20Charlie%20Charles).mp3",
  },
  {
    title: "Ciao Bella",
    artist: "Sfera Ebbasta, ANNA",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20ANNA%20-%20Ciao%20Bella.mp3",
  },
  {
    title: "Triste",
    artist: "Sfera Ebbasta, Feid",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Feid%20-%20Triste.mp3",
  },
  {
    title: "Gol",
    artist: "Sfera Ebbasta, Guè",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Gu%C3%A8%20-%20Gol%20(Visual).mp3",
  },
  {
    title: "15 Piani",
    artist: "Sfera Ebbasta, Marracash",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Marracash%20-%2015%20Piani%20(Visual).mp3",
  },
  {
    title: "Complicato",
    artist: "Sfera Ebbasta, Paky",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Paky%20-%20Complicato%20(Visual).mp3",
  },
  {
    title: "Easy ft. Fivio Foreign",
    artist: "Sfera Ebbasta, Rvssian",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Rvssian%20-%20Easy%20ft.%20Fivio%20Foreign.mp3",
  },
  {
    title: "Mamma Mia",
    artist: "Sfera Ebbasta, Rvssian",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Rvssian%20-%20Mamma%20Mia.mp3",
  },
  {
    title: "Sola ft. Myke Towers",
    artist: "Sfera Ebbasta, Rvssian",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Sfera%20Ebbasta,%20Rvssian%20-%20Sola%20ft.%20Myke%20Towers.mp3",
  },
  {
    title: "M' Manc",
    artist: "Shablo, Geolier, Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Shablo,%20Geolier,%20Sfera%20Ebbasta%20-%20M'%20Manc.mp3",
  },
  {
    title: "WAG1",
    artist: "Simba La Rue - feat. Tedua, Sfera Ebbsta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/Simba%20La%20Rue%20-%20WAG1%20feat.%20Tedua,%20Sfera%20Ebbasta%20(Official%20Lyric%20Video).mp3",
  },
  {
    title: "s!r!",
    artist: "thasup - ft. Lazza, Sfera Ebbasta",
    category: "Sfera Ebbasta",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%8E%A4%20Sfera%20Ebbasta%20Vibes/thasup%20-%20s!r!%20(Visual%20Video)%20ft.%20Lazza,%20Sfera%20Ebbasta.mp3",
  },
];
