// drip-songs.js
window.shivaSongs = [
  // ...

  { /* Playlist di Shiva, "Principino di milano, sto solo aspettando il mio posto da king" 
    "il mio corpo e freddo anche più del mio polso" sku sku" */
    title: "Bad Boy",
    artist: "Finesse ft. Shiva, Capo Plaza, Ava",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Finesse%20-%20Bad%20Boy%20ft.%20Shiva%2C%20Capo%20Plaza%2C%20Ava.mp3",
  },
  {
    title: "Anno Fantastico",
    artist: "Luuchè feat. Shiva, Tony Boy",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Luch%C3%A8%20-%20Anno%20Fantastico%20feat.%20Shiva%2C%20Tony%20Boy%20(Visual%20Video).mp3",
  },
  {
    title: "MILANO LO PRADO",
    artist: "El Jordan 23 X SHIVA prod. by Nes, Toro",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/MILANO%20LO%20PRADO%20-%20El%20Jordan%2023%20X%20SHIVA%20prod.%20by%20Nes%2C%20Toro%20(Visualizer).mp3",
  },
  {
    title: "COME SE NON FOSSI NEI GUAI",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20COME%20SE%20NON%20FOSSI%20NEI%20GUAI%20(Audio).mp3",
  },
  {
    title: "D&G",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20D%26G%20(Audio).mp3",
  },
  {
    title: "MAYBACH",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20MAYBACH%20(Audio).mp3",
  },
  {
    title: "MNGSNT",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20MNGSNT%20(Audio).mp3",
  },
  {
    title: "NEON",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20NEON%20(Audio).mp3",
  },
  {
    title: "NON METTERCI BECCO",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20NON%20METTERCI%20BECCO%20(Audio).mp3",
  },
  {
    title: "OVER (demo)",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20OVER%20(demo)%20(Audio).mp3",
  },
  {
    title: "PARANOIA",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20PARANOIA%20(Audio).mp3",
  },
  {
    title: "SEI PERSA",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20SEI%20PERSA%20(Audio).mp3",
  },
  {
    title: "SNTMNG",
    artist: "SFERA EBBASTA & SHIVA",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/SFERA%20EBBASTA%20%26%20SHIVA%20-%20SNTMNG%20(Audio).mp3",
  },
  {
    title: "Della Gang",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20%20Della%20Gang%20(Audio).mp3",
  },
  {
    title: "100 OPPS",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20100%20OPPS%20(Official%20video).mp3",
  },
  {
    title: "6 AM",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%206%20AM%20(Audio).mp3",
  },
  {
    title: "Alleluia",
    artist: "Shiva feat. Sfera Ebbasta",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Alleluia%20feat.%20Sfera%20Ebbasta%20(Official%20video).mp3",
  },
  {
    title: "Bibidi Bobidi Bu",
    artist: "Shiva feat. Paky",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Bibidi%20Bobidi%20Bu%20feat.%20Paky%20(Official%20video).mp3",
  },
  {
    title: "Bossoli",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Bossoli%20(Prod.%20Adam11).mp3",
  },
  {
    title: "Come No",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Come%20No%20(prod.%20Adam11).mp3",
  },
  {
    title: "Cose che non ho",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Cose%20che%20non%20ho%20(Audio).mp3",
  },
  {
    title: "Cup",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Cup%20(Audio).mp3",
  },
  {
    title: "Fendi belt",
    artist: "Shiva feat. Paky",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Fendi%20belt%20feat.%20Paky%20(Prod.%20Adam11).mp3",
  },
  {
    title: "First Day Out",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20First%20Day%20Out%20(Official%20video).mp3",
  },
  {
    title: "Giovane Re",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Giovane%20Re%20(Official%20video).mp3",
  },
  {
    title: "Gotham",
    artist: "Shiva feat Kid Yugi",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Gotham%20feat.%20Kid%20Yugi%20(Audio).mp3",
  },
  {
    title: "Jackson",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Jackson%20(Prod.%20Adam11).mp3",
  },
  {
    title: "Kooda",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Kooda%20RMX.mp3",
  },
  {
    title: "La mia storia",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20La%20mia%20storia.mp3",
  },
  {
    title: "Lettera a Draco",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Lettera%20a%20Draco%20(Audio).mp3",
  },
  {
    title: "Milano Angels",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Milano%20Angels%20(Audio).mp3",
  },
  {
    title: "Milano Demons",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Milano%20Demons%20(Audio).mp3",
  },
  {
    title: "Milano Shotta Freestyle",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Milano%20Shotta%20Freestyle%20(Official%20video).mp3",
  },
  {
    title: "Mon Fre",
    artist: "Shiva feat. Emils Killa",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Mon%20Fre%20feat.%20Emis%20Killa%20(prod.%20Adam11).mp3",
  },
  {
    title: "Non lo sai",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Non%20lo%20sai%20(Official%20video).mp3",
  },
  {
    title: "Non sto più in zona",
    artist: "Shiva feat. Pyrex",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Non%20sto%20pi%C3%B9%20in%20zona%20feat.%20Pyrex%20(prod.%20Adam11).mp3",
  },
  {
    title: "Pensando a lei",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Pensando%20a%20lei%20(Official%20Video).mp3",
  },
  {
    title: "Pensando a lei 2",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Pensando%20a%20lei%202%20feat.%20Lil%20Tjay.mp3",
  },
  {
    title: "Pluh",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Pluh%20(Official%20video).mp3",
  },
  {
    title: "Polvere",
    artist: "Shiva feat. Tony Boy",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Polvere%20feat.%20Tony%20Boy%20(Audio).mp3",
  },
  {
    title: "Santana",
    artist: "Shiva - (Prod. Adam11)",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Santana%20(prod.%20Adam11).mp3",
  },
  {
    title: "Soldi Puliti",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Soldi%20Puliti%20(Official%20Video).mp3",
  },
  {
    title: "Syrup",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Syrup%20(Official%20video).mp3",
  },
  {
    title: "TAKE 3",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20TAKE%203%20(Prod.%20Adam11).mp3",
  },
  {
    title: "TAKE 4",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20TAKE%204%20%20(Official%20video).mp3",
  },
  {
    title: "TAKE 5",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20TAKE%205%20(Official%20video).mp3",
  },
  {
    title: "Thotiana RMX",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Thotiana%20RMX.mp3",
  },
  {
    title: "Un milione di volte",
    artist: "Shiva feat. Sfera Ebbasta",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Un%20milione%20di%20volte%20feat.%20Sfera%20Ebbasta%20(Audio).mp3",
  },
  {
    title: "Volo Express",
    artist: "Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Volo%20Express%20(Audio).mp3",
  },
  {
    title: "Vorrei",
    artist: "Shiva feat. Lazza",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Shiva%20-%20Vorrei%20feat.%20Lazza%20(Audio).mp3",
  },
  {
    title: "Rip RMX",
    artist: "Side Baby - (prod. by Sick Luke) ft. Shiva",
    category: "Shiva Style",
    file: "https://github.com/Frankie-h7/GiordanoMusic.github.io/raw/refs/heads/main/music/%F0%9F%A5%B6%20Shiva%20Style/Side%20Baby%20-%20Rip%20RMX%20(prod.%20by%20Sick%20Luke)%20ft.%20Shiva.mp3",
  },
];
